#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May 25 20:07:12 2017

@author: dito-maf
"""

1/ Data Inspection

Train_set:
    Data Type= tuple
    Number of samples = 50000
    Shape = [2][50000]
        Train_set[0][i] is encrypted image, with corresponding number is Train_set[1][i]
    Data Type of Train_set[0][] =  np.array(784) of real value between 0 and 1
    Data Type of Train_set[1][] =  float
    

Valid_set:
    super()
    Number of samples =10000

Test_set:
    super()
    Numbe of samples =10000
    
2/ PreprocessData:

Done, the source has divided data for us.
